# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Pinhooker
tagline:          'bloodstock sales analysis'
description:      'using analytical data to make better bloodstock purchasing decisions'
url:              http://phillc73.github.io/pinhooker/
baseurl:          http://phillc73.github.io/pinhooker/

author:
  name:           'Phill Clarke'
  url:            http://www.starkingdom.co.uk
  email:          phill@starkingdom.co.uk

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/phillc73/pinhooker
